### ISSUE TITLE
Missing code in creating-chemical-states

### ISSUE THREAD

**Issue by cdeil** [reaktoro/reaktoro-jupyter-book#3]
The Reaktoro tutorial is really nice! Thank you! :-)

In https://reaktoro.org/tutorials/basics/creating-chemical-states.html at the end this is written:

> he code below demonstrates how to access the phase pairs for which surfaces areas have been set and retrieve their values:

Looks like there is some code example missing?

<img width="1006" alt="Screenshot 2024-01-06 at 21 21 31" src="https://github.com/reaktoro/reaktoro-jupyter-book/assets/852409/09a4881c-33be-4181-82c0-e0d460324df6">

**Comment by allanleal** [comment]
Thanks, @cdeil - Setting surface area values in `ChemicalState` turned out not to be the right approach for chemical kinetics, and this feature was removed. This [commit](https://github.com/reaktoro/reaktoro-jupyter-book/commit/83cfde84810b84dccac01081784c63528fac829d) resolves this issue, but I'm still working on improvements in algorithm before updating the notebooks that compose the website.
